INSERT INTO VOITURE VALUES (1, 'bleue', 'break')
INSERT INTO VOITURE VALUES (2, 'noire', 'berline')
INSERT INTO VOITURE VALUES (3, 'jaune', 'monospace')

INSERT INTO SIEGE VALUES (1, 1, 'noir')

INSERT INTO ROUE (ID, MARQUE, TAILLE, VOITURE_ID) VALUES (1, 'Michelin', '18',1)
INSERT INTO ROUE (ID, MARQUE, TAILLE, VOITURE_ID) VALUES (2, 'michelin', '18',1)
INSERT INTO ROUE (ID, MARQUE, TAILLE, VOITURE_ID) VALUES (3, 'brigestone', '18',2)
INSERT INTO ROUE (ID, MARQUE, TAILLE, VOITURE_ID) VALUES (4, 'bridgestone', '18',2)
INSERT INTO ROUE (ID, MARQUE, TAILLE, VOITURE_ID) VALUES (5, 'bridgestone', '18',3)
INSERT INTO ROUE (ID, MARQUE, TAILLE, VOITURE_ID) VALUES (6, 'bridgestone', '18',3)

INSERT INTO VIS  (ID, FORME, LONGUEUR, DIAMETRE, SIEGE_ID) VALUES (1, 'torx', 50,12, 1)
INSERT INTO VIS (ID, FORME, LONGUEUR, DIAMETRE, SIEGE_ID) VALUES (2, 'torx', 50,12, 1)